### ISSUE TITLE
error: 'add-highlighter' duplicate id: 'bulitin_functions'

### ISSUE THREAD

**Issue by archaistvolts** [lun-4/zig-kak#2]
Thank you for sharing this :+1: :smiley: 

I've installed this plugin with plug.kak. It is highlighting and zig fmt is working.  However i'm getting this error:
```
error running hook WinSetOption(filetype=zig)/: 2:5: 'require-module' 37:1: 
    'add-highlighter' duplicate id: 'bulitin_functions'
```

I've loaded it from kakrc below. I had to change 'set-option window' to 'declare-option str' from the example in the readme.

```
plug "https://github.com/lun-4/zig-kak" load %{
   zig.kak
}

hook global WinSetOption filetype=zig %{
    declare-option str formatcmd 'zig fmt --color off --stdin'
    hook buffer BufWritePre .* %{format}
}
```

Any ideas what is causing this?

**Comment by lun-4** [comment]
I don't load it in as a plug in my configuration, just sourcing it directly, `source "/home/luna/git/zig-kak/zig.kak"`.

I'm still learning the ways of writing stuff like this in kakoune.

**Comment by lun-4** [comment]
`zig-kak` is superseded by having zig syntax on kakoune itself, see: https://github.com/mawww/kakoune/blob/master/rc/filetype/zig.kak

kakoune has not made a release with it yet, though, but i'm closing down `zig-kak`.
